# specify images in group_vars
- hosts: localhost # change if using a seperate machine for building images
  become: True
  gather_facts: yes
  roles:
    - {
        role : toni.buildimages,
        nginx_domain: yd2m.com
      }
  