- import_playbook: builder.yml
  tags: [ build ]

- hosts: targets
  remote_user: root
  gather_facts: yes
  tags: [ host ]
  roles:
    - {
        role: toni.base,
        configure_ipv4_hostname: true,
        configure_ipv6_hostname: false,
        configure_firewall: 'true'
      }
    - {
        role: geerlingguy.ntp,
        ntp_manage_config: true,
        ntp_servers: [
          0.de.pool.ntp.org,
          1.de.pool.ntp.org,
          2.de.pool.ntp.org,
          3.de.pool.ntp.org
        ]
      }      

- hosts: targets
  remote_user: root
  gather_facts: yes
  roles:
    - {
        role: toni.docker,
        docker_network_driver: 'overlay', #trigger swarm
        swarm_interface: "{{ ansible_default_ipv4['interface'] }}", #default wg0
        tags: [ host, docker ]
      }
    - {
        role: toni.openresty,
        openresty_image: "registry.{{ domain }}_openresty:1.19.9.1-alpine-fat",
        force_images: true,
        tags: [ host, openresty ]
      }
    - {
        role: toni.keycloak, 
        auth_bypass: "true",
        tags: [ keycloak ]
      }
    - { 
        role: corteza,
        existing_certs: 'false',
        corteza_dev_enable: false,
        enable_provision: true,
        deploy_name: "corteza",
        include_auth: true,
        create_stack_network: true,
        stack_subnet: "10.10.15.0/24",      
        tags: [ corteza ]
      }