- import_playbook: builder.yml
  tags: [ build ]

- hosts: swarm-01
  remote_user: root
  gather_facts: yes
  tags: [ host ]
  roles:
    - {
        role: toni.base,
        configure_ipv4_hostname: true,
        configure_ipv6_hostname: false,
        configure_firewall: 'true'
      }
    - {
        role: geerlingguy.ntp,
        ntp_manage_config: true,
        ntp_servers: [
          0.de.pool.ntp.org,
          1.de.pool.ntp.org,
          2.de.pool.ntp.org,
          3.de.pool.ntp.org
        ]
      }      

- hosts: swarm-01
  remote_user: root
  gather_facts: yes
  roles:
    - {
        role: toni.docker,
        docker_network_driver: 'overlay', #trigger swarm
        swarm_interface: "{{ ansible_default_ipv4['interface'] }}", #default wg0
        tags: [ host ]
      }
    - {
        role: toni.openresty,
        #docker_network_host: True,
        nginx_network_name: "nginx_net",
        nginx_network_driver: "overlay",
        #docker_network_encrypted: 'true',
        nginx_run_as: "stack",
        force_images: true,
        tags: [ host ]
      }
    - { 
        role: corteza,
        letsencrypt_email: "{{ lets_encrypt_mail }}",
        corteza_dev_enable: false,
        nginx_network_name: "nginx_net",
        nginx_run_as: "stack",
        force_images: false,
        nginx_domain: "{{ domain }}", #  without subdomain
        tags: [ corteza ]
      }