- hosts: targets
  remote_user: r2d2
  become: yes
  gather_facts: yes
  roles:
    - {
        role: toni.keycloak, 
        nginx_subdomain: "key.",
        auth_bypass: "true",
        keycloak_image: "quay.io/keycloak/keycloak:23.0.6",
        tags: [ keycloak ]     
      }
    - { 
        role: corteza,
        nginx_subdomain: "corteza.",
        keycloak_server: "key.{{ domain }}",
        existing_certs: 'false',
        #corteza_image_version: "2023.3.0-dev.1",
        enable_corredor: true,
        enable_provision: true,
        #corteza_dev_version: "2023.3.0-dev.1",
        include_auth: false, 
        create_stack_network: true,
        stack_subnet: "10.10.15.0/24",      
        tags: [ corteza ]
      }
  vars:
    - keycloak_redirect_uris: 
      - "https://corteza.{{ domain }}/*"
      - "https://dev.{{ domain }}/*"
      - "https://one.{{ domain }}/*"
      - "https://admin.{{ domain }}/*"
      - "https://compose.{{ domain }}/*"
      - "https://discovery.{{ domain }}/*"
      - "https://privacy.{{ domain }}/*"
      - "https://reporter.{{ domain }}/*"
      - "https://workflow.{{ domain }}/*"
    - keycloak_web_origins:
      - "https://corteza.{{ domain }}/*"
      - "https://dev.{{ domain }}/*"
      - "https://one.{{ domain }}/*"
      - "https://admin.{{ domain }}/*"
      - "https://compose.{{ domain }}/*"
      - "https://discovery.{{ domain }}/*"
      - "https://privacy.{{ domain }}/*"
      - "https://reporter.{{ domain }}/*"
      - "https://workflow.{{ domain }}/*"