- hosts: targets
  remote_user: root
  gather_facts: yes
  roles:
    - { 
        role: kanban,
        stack_network_name: "corteza_net",
        deploy_name: "kanban",
        include_auth: true,
        #keycloak_client_name:
        #keycloak_client_secret:
        nginx_domain: "hyconcept.de", #  without subdomain
        tags: [ kanban ],
        image_kanban: "registry.hyconcept.de/planka:0.1",
        image_file_kanban: "registry.hyconcept.de_planka:0.1.tar"
      }