---
roles:
 - name: geerlingguy.pip
 - name: atosatto.docker-swarm
 - name: geerlingguy.ntp
 - name: geerlingguy.nfs 
 - name: toni.certificates
   src: git+https://github.com/tnissen375/toni.certificates.git
 - name: toni.docker
   src: git+https://github.com/tnissen375/toni.docker.git
 - name: toni.openresty
   src: git+https://github.com/tnissen375/toni.openresty.git
   version: 3dd7a5b12ce90bdcbeb69472c8dd45cffc34c06d
 - name: toni.buildimages
   src: git+https://github.com/tnissen375/toni.buildimages.git
 - name: toni.base
   src: git+https://github.com/tnissen375/toni.base.git
 - name: toni.dns
   src: git+https://github.com/tnissen375/toni.dns.git
 - name: toni.keycloak
   src: git+https://github.com/tnissen375/toni.keycloak.git
   version: 1efa1d20a6b8596da2273d3ef9b3acc7d2219b9b
