# Copy Image
- hosts: targets
  become: True
  tasks:
  - name: Copy Image
    include_role: { name: toni.buildimages, tasks_from: copy }
  vars:
    include_image_files:
        image: "registry.hyconcept.de_ansible_corredor:2.10-infra-0.39"
  tags: [ copyimage ]

# Renew cert
- hosts: targets
  become: True
  tasks:
  - name: Certbot certificates
    include_role: { name: toni.certificates, tasks_from: certbot_renew }
  vars:
    letsencrypt_domainname: "{{ certbot_server }}"
  tags: [ renew ]
    #letsencrypt_endpoint
    #letsencrypt_domainname
    #letsencrypt_email

# Make
- hosts: targets
  become: True
  tasks:
  - name: Make cmd
    include_role: { name: toni.base, tasks_from: make.yml }
  tags: [ make ]

# Make
- hosts: targets
  become: True
  tasks:
  - name: rsync
    include_role: { name: toni.base, tasks_from: rsync.yml }
  tags: [ rsync ]