# Copy Image
- hosts: targets
  become: True
  gather_facts: yes
  tasks:
  - name: Copy Image
    include_role: { name: toni.buildimages, tasks_from: copy }
  vars:
    include_image_files:
        image: "registry.hyconcept.de_ansible_corredor:2.10-infra-0.39"
  tags: [ copyimage ]

# Renew cert
- hosts: targets
  become: True
  gather_facts: yes
  tasks:
  - name: Certbot certificates
    include_role: { name: toni.certificates, tasks_from: certbot_renew }
  vars:
    letsencrypt_domainname: "{{ certbot_server }}"
  tags: [ renew ]
    #letsencrypt_endpoint
    #letsencrypt_domainname
    #letsencrypt_email

# Make
- hosts: targets
  become: True
  gather_facts: yes
  tasks:
  - name: Make cmd
    include_role: { name: toni.base, tasks_from: make.yml }
  vars:
    cmd: "{{ cmd }}"
    cmd_args: "{{ cmd_args }}"
    stack: "{{ stack }}"
  tags: [ make ]