---
user: "root"
user_path: "/root"
deploy_name: "corteza"
nginx_domain: ""
nginx_subdomain: "{{ deploy_name }}."
enable_ipv6: false # not needed for corteza but if you wanna reach server on ipv6 p.e. keycloak on ipv6 only
enable_backup: false
enable_provision: false
enable_autologin: true
enable_corredor: false
enable_sink: false
auth_proxy: false
auth_proxy_client: "Nginx"
keycloak_realm: "Intern" # the realm which nginx is using in keycloak
keycloak_client_name: "Nginx" # client name in keycloak
keycloak_client_secret: "d3367b2d-85fb-46c0-9fcb-15e2dfeb4d9b" # dummy -> allways change!!
dns_create: false
dns_update: false
nginx_stack: "openresty"
nginx_stack_keep_alive: false
nginx_network_name: "nginx_net"
ssl_certs_path: /etc/nginx/ssl/certs
ssl_private_path: /etc/nginx/ssl/private
create_stack_network: false
stack_network_name: "corteza_net"
stack_subnet: "10.10.15.0/24"
nginx_upstream: "http://{{ deploy_name }}:80"
external_domain: "{{ nginx_subdomain }}{{ nginx_domain }}"
corteza_webapp_enable: "true"
#keycloak_domain: ""
#keycloak_realm: ""
#keycloak_secret: ""
include_auth: "false"
include_xframe: "false" #Nextcloud with Only Office in corteza dashboard
access_group: "corteza"
corteza_mysql_image: "percona:8.0"
corteza_image_version: "2021.9.6"
corteza_image: "cortezaproject/corteza:{{ corteza_image_version }}"
corredor_image: "cortezaproject/corteza-server-corredor:{{ corteza_image_version }}"
#corteza_image: "cortezaproject/corteza-server:{{ corteza_image_version }}"
pdf_image_version: "6"
pdf_image: "thecodingmachine/gotenberg:{{ pdf_image_version }}"
corteza_mysql_user: "corteza"
corteza_mysql_db: "corteza"
corteza_mysql_root_password: "pDsQ2Ahh4W2ojDb4vGeh05n" #dummy, replace in group_vars/all.yml
corteza_mysql_password: "pDsQsg62AW2ojDb4vGeh05nxy" #dummy, replace in group_vars/all.yml
corteza_dev_enable: "false"
corteza_dev_base_url: "dev.{{ nginx_domain }}"
corteza_dev_repository: "https://github.com/tnissen375/corteza-server.git"
corteza_dev_version: "{{ corteza_image_version }}"
corteza_app_enable: "false"
corteza_app_repository: "https://github.com/tnissen375/corteza-webapp-compose.git"
corteza_app_version: "{{ corteza_image_version }}"
#go_dev_image: "deis/go-dev"
#go_dev_image_tag: "v1.32.2"
#image_sshd: "registry.{{ domain }}/sshd:3.14"
#image_file_sshd: "registry.{{ domain }}_sshd:3.14.tar"
host_ssh_port: 2223
image_go_dev_tag: "v1.32.2"
image_go_dev_ssh: "registry.{{ domain }}/go_dev_ssh:{{ image_go_dev_tag }}"
image_file_go_dev_ssh: "registry.{{ domain }}_go_dev_ssh:{{ image_go_dev_tag }}.tar"
image_node_ssh_tag: "14"
image_node_ssh: "registry.{{ domain }}/node_ssh:{{ image_node_ssh_tag }}"
image_file_node_ssh: "registry.{{ domain }}_node_ssh:{{ image_node_ssh_tag }}.tar"

nginx_conf_dir: "/etc/nginx"
container_cert_path: "/etc/ssl/dummy-ssl-fallback.crt"
container_key_path: "/etc/ssl/dummy-ssl-fallback.key"

dir_exists:
  - "/etc/nginx/conf.d"
  - "{{ user_path }}/{{ deploy_name }}"
  - "{{ user_path }}/{{ deploy_name }}/corredor"
  - "{{ user_path }}/{{ deploy_name }}/corredor/client-scripts"
  - "{{ user_path }}/{{ deploy_name }}/corredor/server-scripts"
  - "{{ user_path }}/{{ deploy_name }}/ansible"
  - "{{ user_path }}/{{ deploy_name }}/backup"
  - "{{ user_path }}/{{ deploy_name }}/src"