TAIL=20
d=$$(date +%Y_%m_%d)

DB := $$(docker ps -a | grep "Up" | awk '{print $$NF}' | grep -w "{{ deploy_name }}_{{ deploy_name }}_db\.*")
CORTEZA := $$(docker ps -a | grep "Up" | awk '{print $$NF}' | grep -w "{{ deploy_name }}_{{ deploy_name }}\.*")
NGINX := $$(docker ps -a | grep "Up" | awk '{print $$NF}' | grep -w "{{ nginx_stack }}_nginx-proxy\.*")
{% if corteza_dev_enable is defined and corteza_dev_enable|bool==false %}
BIN := "corteza-server"
{% else %}
BIN := "/go/src/corteza-server/gin-bin"
{% endif %}

rm:
	docker stack rm {{ deploy_name }}

deploy:
	docker stack deploy -c docker-compose.yml {{ deploy_name }} && docker exec -it $(NGINX) nginx -s reload

sinkhelp:
	docker exec $(CORTEZA) $(BIN) sink signature -h

sink:
	docker exec $(CORTEZA) $(BIN) sink signature --method POST --content-type email
{% if corteza_dev_enable is defined and corteza_dev_enable|bool==true %}
debugdev:
	docker exec -d $(CORTEZA) sh -c 'kill $$(pgrep dlv) || echo "dlv not running" && dlv attach -l 127.0.0.1:42325 --headless --log=true --accept-multiclient --api-version=2 $$(pgrep gin-bin)'
{% endif %}

ps:
	docker stack ps {{ deploy_name }} --no-trunc

log:
	docker service logs -f $(CORTEZA) --tail ${TAIL} --raw

logdb:
	docker service logs -f $(DB) --tail ${TAIL}

exec:
	docker exec -it $(CORTEZA) /bin/sh

execdb:
	docker exec -it $(DB) /bin/bash

bckup:
	docker exec $(CORTEZA) sh -c 'exec tar -cv /data' | gzip > {{ user_path }}/{{ deploy_name }}/backup/data_"$d".tar.gz

restore:
	gunzip -c $(file) | docker cp - $(CORTEZA):/

bckupdb:
	docker exec $(DB) sh -c 'exec mysqldump -uroot -p"$$MYSQL_ROOT_PASSWORD" {{ corteza_mysql_db }}' | gzip > {{ user_path }}/{{ deploy_name }}/backup/{{ corteza_mysql_db }}_db_"$d".sql.gz

restoredb:
	gunzip -c $(file) | docker exec -i $(DB) sh -c 'exec mysql -u root -p"$$MYSQL_ROOT_PASSWORD" {{ corteza_mysql_db }}'

purge:
	find {{ user_path }}/{{ deploy_name }}/backup/*.sql.gz  -mtime +10 -delete &> /dev/null && find {{ user_path }}/{{ deploy_name }}/data_*.gz  -mtime +10 -delete &> /dev/null

{% if corteza_dev_enable is defined and corteza_dev_enable|bool==true %}

apps:
	docker exec $(CORTEZA) sh -c 'exec make --directory=/go/src/corteza-server/webapp'

vendor:
	docker exec $(CORTEZA) sh -c 'exec go mod vendor'

realize:
	docker exec $(CORTEZA) sh -c 'exec make realize'
{% endif %}