---
user: "root"
user_path: "/root"
deploy_name: "kanban"
nginx_subdomain: "{{ deploy_name }}."
dns_create: false
dns_update: false
nginx_stack: "openresty"
nginx_stack_keep_alive: true
nginx_network_name: "nginx_net"
ssl_certs_path: /etc/nginx/ssl/certs
ssl_private_path: /etc/nginx/ssl/private
create_stack_network: false
stack_network_name: "corteza_net"
stack_subnet: "10.10.15.0/24"
nginx_upstream: "http://{{ deploy_name }}:1337"
external_domain: "{{ nginx_subdomain }}{{ nginx_domain }}"
corteza_webapp_enable: "true"
#keycloak_domain: ""
#keycloak_realm: ""
#keycloak_secret: ""
include_auth: "false"
access_group: "web"
corteza_sink_setup: false
kanban_postgres_user: "planka"
kanban_postgres_db: "planka"
kanban_postgres_password: "pDsQsg62AW2ojDb4vGeh05nxy" #dummy, replace in group_vars/all.yml
kanban_postgres_version: 13

image_kanban_tag: "0.1"
image_kanban: "registry.{{ domain }}/planka:{{ image_kanban_tag }}"
image_file_kanban: "registry.{{ domain }}_planka:{{ image_kanban_tag }}.tar"
host_ssh_port: 2229

nginx_conf_dir: "/etc/nginx"
container_cert_path: "/etc/ssl/dummy-ssl-fallback.crt"
container_key_path: "/etc/ssl/dummy-ssl-fallback.key"

dir_exists:
  - "/etc/nginx/conf.d"
  - "{{ user_path }}/{{ deploy_name }}/backup"
  - "{{ user_path }}/{{ deploy_name }}/src"